version: '3.4'

x-logging: &logging
  driver: json-file
  options:
    max-size: 100m
    max-file: '5'

services:
  bot:
    image: mayoshia/pawa
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 6G
    environment:
      - BOT_DATA_DIR=/data
      - BOT_HTTP_PORT=3000
      - BOT_LEAVE_GUILD_AFTER=365
      - BOT_MAINTENANCE=false
      - BOT_MP3_VBR=false
      - BOT_STANDALONE=true
      - BOT_TOKEN=NTYzNDQzNTI4NzI3MDAzMTM3.XKZZrQ.GKAZ_andI15jUwW10sAEqNFK3rw
      - DS_BUCKET=recordings
      - TZ=Europe/Moscow
      - JAVA_TOOL_OPTIONS=-Dlog4j.configurationFile=log4j2.xml
    ports:
      - "127.0.0.1:3000:3000"
    restart: on-failure:100
    volumes:
      - ./recordings:/app/recordings
      - ./logs:/app/logs
    logging:
      <<: *logging
